
name: conc
version: '0.1.0.0'
category: Data Structures
author: Romain Ruetschi
maintainer: romain.ruetschi@gmail.com
copyright: 2017 Romain Ruetschi
license: BSD3
github: romac/conc
synopsis: Conc-Tree lists and ropes
description: See README at <https://github.com/sol/hpack#readme> 

extra-source-files:
  - README.md
  - LICENSE

dependencies:
  - base >=4.7 && <5
  - deepseq
  - vector
  - primitive

ghc-options:
  - -Wall
  - -fno-warn-unused-top-binds 
  - -fno-warn-unused-matches
  - -fno-warn-name-shadowing

library:
  source-dirs: src
  exposed-modules:
    - Conc.Tree
    - Conc.Tree.Buffer

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck

